modLoader = "javafml"
loaderVersion = "[3,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "cca_architectury_port"
version = "${version}"
displayName = "Cardinal Components API(Architectury port)"
authors = "Progames723 and the original developers!"
description = '''
yes this is literally a port
'''
logoFile = "assets/icon.png"

[[dependencies.cca_architectury_port]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cca_architectury_port]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cca_architectury_port]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"